apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  clusterIP: 
  ports:
  - name: port-1
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: port-2
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app: rabbitmq
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
